version: '3.7'
services:
    postgres_kidternship_25:
        image: postgres:15
        restart: unless-stopped
        environment:
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
